### ISSUE TITLE
Donation feature - Scenario 1

### ISSUE THREAD

**Issue by zhibek** [thebiggive/regression-tests#2]
```
Make a matched donation
As a donor
I want payment to be taken for a match campaign
So that I can support my chosen charity with a doubled donation

Scenario: Match funds available and payment is processed successfully, before match fund reservation expires
Given that I am on my chosen Donate page
When I enter an amount between £5 and £25,000
And I choose a preference for Gift Aid, charity comms and TBG comms
And I press Donate
Then I am taken to Charity Checkout pages, where I can complete my other donation information (we can probably gloss over the detail for this a bit, as the steps are expected to change shortly)
When my bank approves the charge and the payment steps took less than 15 minutes
Then I should be redirected to a Thank You confirmation page
And I should see an initial message saying the donation succeeded
When I wait 5 seconds
Then I should see my Charity Checkout transaction ID
And I should see my matched amount is the same as my donation amount
And I should see the total value of my donation is double my donation amount, plus any Gift Aid
```

~The base URL for this (and all other tests) will be:~
~https://regtest1-thebiggive.cs105.force.com/s/~

~There is a campaign setup on this organisation (but it's currently showing errors):~
~https://regtest1-thebiggive.cs105.force.com/s/campaign?cId=a051w000001OtHOAA0~

@NoelLH Can you guide us through the steps to get this campaign working? Or alternatively, if there's a working campaign in another organisation we can use temporarily, please let us know (I've checked through your sandbox orgs and UAT, but I've hit blockers with each).

**Comment by zhibek** [comment]
@mohamedMahdyCc The base URL for the tests is TBC, but we can use the following base URL for testing for now:
https://donate-staging.thebiggivetest.org.uk

We can use this donate page (styling TBC) for testing for now:
https://donate-staging.thebiggivetest.org.uk/donate/a051r00001NogBOAAZ

**Comment by NoelLH** [comment]
@zhibek sorry the test regular campaign wasn't working, it looks like the [Salesforce frontend's version of the 'view campaign' page](https://regtest1-thebiggive.cs105.force.com/s/campaign?cId=a051w000001OtHOAA0) required a non-blank Preview date to load. I've now set this date on [the campaign](https://thebiggive--regtest1.lightning.force.com/lightning/r/CCampaign__c/a051w000001OtHOAA0/view) - typically when charities actually make their own campaign the normal way this should be automatically set to a few days before the start.

You should have access on the RegTest1 sandbox to view & edit objects and also view the deployed code online (from Setup > Developer Console) though hopefully this won't generally be necessary!

A deployed version of the new frontend targeting the same RegTest1 Salesforce instance is almost ready to go - I'll link it on #bdd on Slack when it's working, and have added a column to the SF orgs sheet to make it clearer where to find this.
